//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 09:00:28 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soapservice.ishop.by/")
package by.ishop.data.product;
