
package by.ishop.soapservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoEntryPricingInfo", targetNamespace = "http://soapservice.ishop.by/")
public class NoEntryPricingInfo_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoEntryPricingInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NoEntryPricingInfo_Exception(String message, NoEntryPricingInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NoEntryPricingInfo_Exception(String message, NoEntryPricingInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: by.ishop.soapservice.NoEntryPricingInfo
     */
    public NoEntryPricingInfo getFaultInfo() {
        return faultInfo;
    }

}
