//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 04:59:00 PM MSK 
//


package by.ishop.data.product;

import javax.xml.bind.annotation.XmlRegistry;
import java.math.BigDecimal;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.ishop.data.product package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.ishop.data.product
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductEntry }
     * 
     */
    // test generation
    public static ProductEntry createProductEntry() {
        ProductEntry ret = new ProductEntry();
        ret.setName("Canon EOS 5D");
        ret.setImgURL("/img/canon.png");
        ret.setPrice(new BigDecimal("1800"));
        {
            Specification spec = new Specification();
            spec.setPropName("Sensor");
            spec.setPropValue("35.8 x 23.9 mm CMOS (full-frame)");
            ret.getCharacteristics().add(spec);
        }
        {
            Specification spec = new Specification();
            spec.setPropName("Weight");
            spec.setPropValue("810 g");
            ret.getCharacteristics().add(spec);
        }
        return ret;
    }

    /**
     * Create an instance of {@link Specification }
     * 
     */
    public Specification createSpecification() {
        return new Specification();
    }

}
